# Generated by Django 3.1.7 on 2021-03-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='store',
            new_name='user',
        ),
    ]
